# Generated by Django 5.1.5 on 2026-02-19

import secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('github_url', models.URLField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('followers', models.PositiveIntegerField(default=0)),
                ('following', models.PositiveIntegerField(default=0)),
                ('public_repos', models.PositiveIntegerField(default=0)),
                ('totals', models.JSONField(blank=True, default=dict)),
                (
                    'generation_status',
                    models.CharField(
                        choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')],
                        default='processing',
                        max_length=20,
                    ),
                ),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='RepoSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('html_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('primary_language', models.CharField(blank=True, max_length=100)),
                ('language_breakdown', models.JSONField(blank=True, default=dict)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('forks', models.PositiveIntegerField(default=0)),
                ('open_issues', models.PositiveIntegerField(default=0)),
                ('watchers', models.PositiveIntegerField(default=0)),
                ('size_kb', models.PositiveIntegerField(default=0)),
                ('commits_30d', models.PositiveIntegerField(default=0)),
                ('activity_score', models.FloatField(default=0)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('is_fork', models.BooleanField(default=False)),
                ('pos_x', models.FloatField(default=0)),
                ('pos_y', models.FloatField(default=0)),
                ('pos_z', models.FloatField(default=0)),
                (
                    'world',
                    models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='repos', to='worlds.world'),
                ),
            ],
            options={
                'ordering': ['-activity_score', '-stars'],
            },
        ),
        migrations.CreateModel(
            name='RenderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.PositiveIntegerField(default=1)),
                ('layout_version', models.CharField(default='v1', max_length=20)),
                ('density_level', models.FloatField(default=1.0)),
                ('lighting_profile', models.CharField(default='neo_city', max_length=50)),
                ('enable_particles', models.BooleanField(default=True)),
                (
                    'world',
                    models.OneToOneField(on_delete=models.deletion.CASCADE, related_name='render_config', to='worlds.world'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='LanguageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('percent', models.FloatField(default=0)),
                ('color_token', models.CharField(default='primary-blue', max_length=20)),
                (
                    'world',
                    models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='languages', to='worlds.world'),
                ),
            ],
            options={
                'ordering': ['-percent'],
                'unique_together': {('world', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ShareToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=32, unique=True)),
                ('is_public', models.BooleanField(default=True)),
                ('poster_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                (
                    'world',
                    models.OneToOneField(on_delete=models.deletion.CASCADE, related_name='share_token', to='worlds.world'),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='world',
            index=models.Index(fields=['username', 'generated_at'], name='worlds_world_usernam_4f00ce_idx'),
        ),
        migrations.AddIndex(
            model_name='world',
            index=models.Index(fields=['generation_status'], name='worlds_world_generat_66b0e7_idx'),
        ),
        migrations.AddIndex(
            model_name='reposnapshot',
            index=models.Index(fields=['primary_language'], name='worlds_repos_primary_451c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='reposnapshot',
            index=models.Index(fields=['stars'], name='worlds_repos_stars_5d7d12_idx'),
        ),
    ]
