# Generated by Django 5.1.5 on 2026-02-19 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reposnapshot',
            new_name='worlds_repo_primary_a209f9_idx',
            old_name='worlds_repos_primary_451c0f_idx',
        ),
        migrations.RenameIndex(
            model_name='reposnapshot',
            new_name='worlds_repo_stars_a523ae_idx',
            old_name='worlds_repos_stars_5d7d12_idx',
        ),
        migrations.RenameIndex(
            model_name='world',
            new_name='worlds_worl_usernam_059d02_idx',
            old_name='worlds_world_usernam_4f00ce_idx',
        ),
        migrations.RenameIndex(
            model_name='world',
            new_name='worlds_worl_generat_3477f3_idx',
            old_name='worlds_world_generat_66b0e7_idx',
        ),
    ]
